import type {
  Budget,
  KaizoData,
  ServiceEntry,
  ServiceOrderPart,
  TimelineEvent,
} from "./types";

const at = (days: number, hour = 9, minute = 0) => {
  const value = new Date();
  value.setDate(value.getDate() + days);
  value.setHours(hour, minute, 0, 0);
  return value.toISOString();
};

const localDateTime = (days: number, hour = 17, minute = 0) => {
  const value = new Date();
  value.setDate(value.getDate() + days);
  value.setHours(hour, minute, 0, 0);
  const offset = value.getTimezoneOffset();
  return new Date(value.getTime() - offset * 60_000).toISOString().slice(0, 16);
};

const event = (
  id: string,
  date: string,
  action: string,
  description: string,
): TimelineEvent => ({ id, date, action, description });
const part = (
  id: string,
  name: string,
  cost: number,
  price: number,
): ServiceOrderPart => ({
  id,
  name,
  supplier: "Distribuidora local",
  quantity: 1,
  unitCost: cost,
  unitPrice: price,
  responsibility: "Oficina",
  additionalCosts: [],
});

const entries: ServiceEntry[] = [
  {
    id: "entry-1",
    number: 2009,
    customerId: "c4",
    vehicleId: "v4",
    mileageIn: 34120,
    reportedProblem:
      "Ruído na suspensão dianteira ao passar por irregularidades.",
    technicalNotes: "",
    recommendations: "",
    tags: ["Suspensão"],
    priority: "Alta",
    initialDueDate: localDateTime(1, 16),
    notes: "Atendimento aguardando diagnóstico.",
    status: "Em diagnóstico",
    evidences: [],
    createdAt: at(0, 8, 15),
    updatedAt: at(0, 8, 15),
    timeline: [
      event(
        "te-1",
        at(0, 8, 15),
        "Atendimento criado",
        "Entrada do veículo e relato inicial registrados.",
      ),
    ],
  },
  {
    id: "entry-2",
    number: 2008,
    customerId: "c1",
    vehicleId: "v1",
    mileageIn: 78650,
    reportedProblem: "Luz de injeção acesa e perda de potência.",
    technicalNotes: "Falha intermitente no cilindro 2.",
    recommendations: "Substituir bobina e velas.",
    tags: ["Injeção eletrônica"],
    priority: "Alta",
    initialDueDate: localDateTime(1, 17),
    notes: "",
    status: "Orçamento criado",
    evidences: [],
    createdAt: at(0, 8, 40),
    updatedAt: at(0, 10),
    timeline: [
      event("te-2", at(0, 8, 40), "Atendimento criado", "Veículo recebido."),
      event(
        "te-3",
        at(0, 9, 40),
        "Diagnóstico registrado",
        "Falha de ignição confirmada.",
      ),
      event(
        "te-4",
        at(0, 10),
        "Orçamento criado",
        "Orçamento iniciado como rascunho.",
      ),
    ],
  },
  {
    id: "entry-3",
    number: 2007,
    customerId: "c2",
    vehicleId: "v2",
    mileageIn: 62300,
    reportedProblem: "Revisão periódica e ruído ao frear.",
    technicalNotes: "Pastilhas dianteiras no limite de desgaste.",
    recommendations: "Substituir pastilhas e revisar fluido.",
    tags: ["Freio"],
    priority: "Normal",
    initialDueDate: localDateTime(1, 18),
    notes: "",
    status: "Orçamento criado",
    evidences: [],
    createdAt: at(-1, 14),
    updatedAt: at(0, 9),
    timeline: [
      event("te-5", at(-1, 14), "Atendimento criado", "Revisão registrada."),
      event(
        "te-6",
        at(0, 9),
        "Orçamento enviado",
        "Aguardando decisão do cliente.",
      ),
    ],
  },
  {
    id: "entry-4",
    number: 2006,
    customerId: "c3",
    vehicleId: "v3",
    mileageIn: 47980,
    reportedProblem: "Higienização interna e polimento técnico.",
    technicalNotes: "Pintura com microrriscos e bancos com manchas leves.",
    recommendations: "Manutenção semestral da proteção.",
    tags: ["Estética"],
    priority: "Normal",
    initialDueDate: localDateTime(2, 15),
    notes: "",
    status: "Orçamento criado",
    evidences: [],
    createdAt: at(-1, 10),
    updatedAt: at(0, 10, 30),
    timeline: [
      event(
        "te-7",
        at(-1, 10),
        "Atendimento criado",
        "Serviços estéticos solicitados.",
      ),
      event(
        "te-8",
        at(0, 10, 30),
        "Orçamento aprovado",
        "Cliente aprovou o orçamento localmente.",
      ),
    ],
  },
  {
    id: "entry-5",
    number: 2005,
    customerId: "c1",
    vehicleId: "v1",
    mileageIn: 78120,
    reportedProblem: "Alinhamento e balanceamento.",
    technicalNotes: "Pneu dianteiro com desgaste irregular.",
    recommendations: "Avaliar substituição futura.",
    tags: ["Suspensão"],
    priority: "Normal",
    initialDueDate: localDateTime(2, 14),
    notes: "",
    status: "Encerrado",
    evidences: [],
    createdAt: at(-2, 11),
    updatedAt: at(-1, 16),
    timeline: [
      event(
        "te-9",
        at(-2, 11),
        "Atendimento criado",
        "Solicitação registrada.",
      ),
      event(
        "te-10",
        at(-1, 16),
        "Orçamento recusado",
        "Cliente recusou o orçamento.",
      ),
    ],
  },
  {
    id: "entry-6",
    number: 2004,
    customerId: "c2",
    vehicleId: "v2",
    mileageIn: 61900,
    reportedProblem: "Troca preventiva da correia dentada.",
    technicalNotes: "Prazo recomendado atingido.",
    recommendations: "Trocar kit completo.",
    tags: ["Revisão periódica"],
    priority: "Normal",
    initialDueDate: localDateTime(1, 16),
    notes: "",
    status: "Encerrado",
    evidences: [],
    createdAt: at(-2, 8),
    updatedAt: at(-1, 10),
    timeline: [
      event(
        "te-11",
        at(-2, 8),
        "Atendimento criado",
        "Manutenção preventiva registrada.",
      ),
      event(
        "te-12",
        at(-1, 10),
        "OS gerada",
        "Orçamento aprovado convertido em ordem de serviço.",
      ),
    ],
  },
  {
    id: "entry-7",
    number: 2003,
    customerId: "c1",
    vehicleId: "v1",
    mileageIn: 77400,
    reportedProblem: "Falha na partida pela manhã.",
    technicalNotes: "Bateria com baixa capacidade de partida.",
    recommendations: "Substituir bateria e revisar alternador.",
    tags: ["Elétrica"],
    priority: "Alta",
    initialDueDate: localDateTime(0, 17),
    notes: "",
    status: "Encerrado",
    evidences: [],
    createdAt: at(-2, 15),
    updatedAt: at(0, 8),
    timeline: [
      event(
        "te-13",
        at(-2, 15),
        "Atendimento criado",
        "Falha elétrica registrada.",
      ),
      event("te-14", at(-1, 9), "OS gerada", "Serviço autorizado."),
      event(
        "te-15",
        at(0, 8),
        "Serviço iniciado",
        "Veículo direcionado para execução.",
      ),
    ],
  },
  {
    id: "entry-8",
    number: 2002,
    customerId: "c3",
    vehicleId: "v3",
    mileageIn: 47200,
    reportedProblem: "Troca de óleo e filtros.",
    technicalNotes: "Manutenção periódica dentro do prazo.",
    recommendations: "Retornar em 10 mil km.",
    tags: ["Revisão periódica"],
    priority: "Normal",
    initialDueDate: localDateTime(0, 12),
    notes: "",
    status: "Encerrado",
    evidences: [],
    createdAt: at(-3, 9),
    updatedAt: at(0, 11),
    timeline: [
      event("te-16", at(-3, 9), "Atendimento criado", "Revisão registrada."),
      event("te-17", at(-2, 10), "OS gerada", "Orçamento aprovado."),
      event(
        "te-18",
        at(0, 11),
        "Serviço finalizado",
        "Controle de qualidade concluído.",
      ),
    ],
  },
  {
    id: "entry-9",
    number: 2001,
    customerId: "c4",
    vehicleId: "v4",
    mileageIn: 32900,
    reportedProblem: "Revisão de freios e troca do fluido.",
    technicalNotes: "Sistema revisado e liberado.",
    recommendations: "Nova inspeção em 12 meses.",
    tags: ["Freio"],
    priority: "Normal",
    initialDueDate: localDateTime(-4, 14),
    notes: "",
    status: "Encerrado",
    evidences: [],
    createdAt: at(-5, 9),
    updatedAt: at(-4, 16),
    timeline: [
      event("te-19", at(-5, 9), "Atendimento criado", "Revisão solicitada."),
      event(
        "te-20",
        at(-4, 16),
        "Veículo entregue",
        "Serviço pago e veículo entregue.",
      ),
    ],
  },
];

const budgets: Budget[] = [
  {
    id: "budget-1",
    number: 3008,
    entryId: "entry-2",
    status: "Rascunho",
    parts: [part("bp-1", "Bobina de ignição", 220, 340)],
    labor: [
      {
        id: "bl-1",
        name: "Diagnóstico e substituição",
        estimatedHours: 1.5,
        hourlyRate: 0,
        price: 280,
      },
    ],
    quoteMessage: "Diagnóstico concluído. Revise os itens recomendados.",
    dueDate: localDateTime(1, 17),
    createdAt: at(0, 10),
    updatedAt: at(0, 10),
    timeline: [
      event("tb-1", at(0, 10), "Orçamento criado", "Rascunho iniciado."),
    ],
  },
  {
    id: "budget-2",
    number: 3007,
    entryId: "entry-3",
    status: "Aguardando aprovação",
    parts: [part("bp-2", "Pastilhas de freio dianteiras", 185, 290)],
    labor: [
      {
        id: "bl-2",
        name: "Troca de pastilhas e revisão",
        estimatedHours: 1.5,
        hourlyRate: 0,
        price: 280,
      },
    ],
    quoteMessage:
      "Itens necessários para restaurar a segurança do sistema de freios.",
    dueDate: localDateTime(1, 18),
    createdAt: at(-1, 16),
    updatedAt: at(0, 9),
    timeline: [
      event("tb-2", at(-1, 16), "Orçamento criado", "Valores registrados."),
      event("tb-3", at(0, 9), "Orçamento enviado", "Aguardando aprovação."),
    ],
  },
  {
    id: "budget-3",
    number: 3006,
    entryId: "entry-4",
    status: "Aprovado",
    parts: [],
    labor: [
      {
        id: "bl-3",
        name: "Polimento técnico",
        estimatedHours: 4,
        hourlyRate: 0,
        price: 520,
      },
      {
        id: "bl-4",
        name: "Higienização interna",
        estimatedHours: 3,
        hourlyRate: 0,
        price: 300,
      },
    ],
    quoteMessage: "Serviços estéticos aprovados.",
    dueDate: localDateTime(2, 15),
    createdAt: at(-1, 11),
    updatedAt: at(0, 10, 30),
    timeline: [
      event("tb-4", at(-1, 11), "Orçamento enviado", "Valores apresentados."),
      event(
        "tb-5",
        at(0, 10, 30),
        "Orçamento aprovado",
        "Aprovação registrada localmente.",
      ),
    ],
  },
  {
    id: "budget-4",
    number: 3005,
    entryId: "entry-5",
    status: "Recusado",
    parts: [],
    labor: [
      {
        id: "bl-5",
        name: "Alinhamento e balanceamento",
        estimatedHours: 1,
        hourlyRate: 0,
        price: 180,
      },
    ],
    quoteMessage: "",
    dueDate: localDateTime(2, 14),
    createdAt: at(-2, 13),
    updatedAt: at(-1, 16),
    timeline: [
      event(
        "tb-6",
        at(-2, 13),
        "Orçamento enviado",
        "Orçamento disponibilizado.",
      ),
      event(
        "tb-7",
        at(-1, 16),
        "Orçamento recusado",
        "Cliente não autorizou o serviço.",
      ),
    ],
  },
  {
    id: "budget-5",
    number: 3004,
    entryId: "entry-6",
    status: "Aprovado",
    parts: [part("bp-3", "Kit correia dentada", 410, 590)],
    labor: [
      {
        id: "bl-6",
        name: "Troca do kit de correia",
        estimatedHours: 3,
        hourlyRate: 0,
        price: 480,
      },
    ],
    quoteMessage: "Manutenção preventiva autorizada.",
    dueDate: localDateTime(1, 16),
    createdAt: at(-2, 10),
    updatedAt: at(-1, 10),
    timeline: [
      event(
        "tb-8",
        at(-1, 9),
        "Orçamento aprovado",
        "Cliente autorizou o serviço.",
      ),
    ],
  },
  {
    id: "budget-6",
    number: 3003,
    entryId: "entry-7",
    status: "Aprovado",
    parts: [part("bp-4", "Bateria 60 Ah", 390, 560)],
    labor: [
      {
        id: "bl-7",
        name: "Substituição e teste de carga",
        estimatedHours: 1,
        hourlyRate: 0,
        price: 180,
      },
    ],
    quoteMessage: "Serviço elétrico autorizado.",
    dueDate: localDateTime(0, 17),
    createdAt: at(-2, 17),
    updatedAt: at(-1, 9),
    timeline: [
      event(
        "tb-9",
        at(-1, 9),
        "Orçamento aprovado",
        "Cliente autorizou o serviço.",
      ),
    ],
  },
  {
    id: "budget-7",
    number: 3002,
    entryId: "entry-8",
    status: "Aprovado",
    parts: [part("bp-5", "Kit óleo e filtros", 210, 340)],
    labor: [
      {
        id: "bl-8",
        name: "Troca de óleo e filtros",
        estimatedHours: 1.5,
        hourlyRate: 0,
        price: 260,
      },
    ],
    quoteMessage: "Revisão concluída.",
    dueDate: localDateTime(0, 12),
    createdAt: at(-3, 11),
    updatedAt: at(-2, 10),
    timeline: [
      event("tb-10", at(-2, 10), "Orçamento aprovado", "Serviço autorizado."),
    ],
  },
  {
    id: "budget-8",
    number: 3001,
    entryId: "entry-9",
    status: "Aprovado",
    parts: [part("bp-6", "Fluido de freio", 55, 95)],
    labor: [
      {
        id: "bl-9",
        name: "Revisão completa de freios",
        estimatedHours: 2,
        hourlyRate: 0,
        price: 475,
      },
    ],
    quoteMessage: "Serviço concluído e entregue.",
    dueDate: localDateTime(-4, 14),
    createdAt: at(-5, 11),
    updatedAt: at(-5, 14),
    timeline: [
      event("tb-11", at(-5, 14), "Orçamento aprovado", "Serviço autorizado."),
    ],
  },
];

export const seedData: KaizoData = {
  company: {
    id: "company-1",
    name: "Oficina Demo",
    businessType: "Mecânica",
    whatsapp: "(11) 99999-0000",
    address: "Av. das Oficinas, 240 · São Paulo, SP",
    quoteMessage:
      "Selecionamos as soluções recomendadas para seu veículo. Conte com a gente.",
    accent: "#E5484D",
  },
  customers: [
    {
      id: "c1",
      name: "João da Silva",
      phone: "(11) 99999-9999",
      cpf: "123.456.789-00",
      notes: "Prefere contato por WhatsApp.",
      createdAt: at(-90),
    },
    {
      id: "c2",
      name: "Maria Oliveira",
      phone: "(11) 98888-1212",
      createdAt: at(-70),
    },
    {
      id: "c3",
      name: "Carlos Santos",
      phone: "(11) 97777-3434",
      notes: "Cliente recorrente.",
      createdAt: at(-50),
    },
    {
      id: "c4",
      name: "Ana Costa",
      phone: "(11) 96666-4545",
      createdAt: at(-30),
    },
  ],
  vehicles: [
    {
      id: "v1",
      customerId: "c1",
      plate: "ABC1D23",
      brand: "Honda",
      model: "Civic",
      version: "EX 2.0 Flex",
      year: 2018,
      color: "Prata",
      vehicleCategory: "sedan",
      mileage: 78650,
      fuel: "Flex",
    },
    {
      id: "v2",
      customerId: "c2",
      plate: "BRA2E19",
      brand: "Volkswagen",
      model: "Gol",
      version: "1.0",
      year: 2019,
      color: "Branco",
      vehicleCategory: "hatch",
      mileage: 62300,
      fuel: "Flex",
    },
    {
      id: "v3",
      customerId: "c3",
      plate: "KZO2A20",
      brand: "Chevrolet",
      model: "Onix",
      version: "LT",
      year: 2020,
      color: "Preto",
      vehicleCategory: "hatch",
      mileage: 47980,
      fuel: "Flex",
    },
    {
      id: "v4",
      customerId: "c4",
      plate: "KAJ4Z21",
      brand: "Toyota",
      model: "Corolla",
      version: "GLi 2.0",
      year: 2021,
      color: "Cinza",
      vehicleCategory: "sedan",
      mileage: 34120,
      fuel: "Flex",
    },
  ],
  entries,
  budgets,
  orders: [
    {
      id: "order-1",
      number: 854,
      entryId: "entry-6",
      budgetId: "budget-5",
      status: "Aguardando início",
      createdAt: at(-1, 10),
      updatedAt: at(-1, 10),
      timeline: [
        event(
          "to-1",
          at(-1, 10),
          "OS gerada",
          "Ordem criada a partir do orçamento aprovado.",
        ),
      ],
    },
    {
      id: "order-2",
      number: 853,
      entryId: "entry-7",
      budgetId: "budget-6",
      status: "Em serviço",
      createdAt: at(-1, 9),
      updatedAt: at(0, 8),
      timeline: [
        event(
          "to-2",
          at(-1, 9),
          "OS gerada",
          "Ordem criada a partir do orçamento aprovado.",
        ),
        event(
          "to-3",
          at(0, 8),
          "Serviço iniciado",
          "Execução iniciada pela equipe.",
        ),
      ],
    },
    {
      id: "order-3",
      number: 852,
      entryId: "entry-8",
      budgetId: "budget-7",
      status: "Finalizado",
      createdAt: at(-2, 10),
      updatedAt: at(0, 11),
      timeline: [
        event("to-4", at(-2, 10), "OS gerada", "Serviço autorizado."),
        event("to-5", at(0, 8), "Serviço iniciado", "Execução iniciada."),
        event(
          "to-6",
          at(0, 11),
          "Serviço finalizado",
          "Controle de qualidade aprovado.",
        ),
      ],
    },
    {
      id: "order-4",
      number: 851,
      entryId: "entry-9",
      budgetId: "budget-8",
      status: "Entregue",
      createdAt: at(-5, 14),
      updatedAt: at(-4, 16),
      timeline: [
        event("to-7", at(-5, 14), "OS gerada", "Serviço autorizado."),
        event("to-8", at(-4, 14), "Serviço finalizado", "Revisão concluída."),
        event("to-9", at(-4, 16), "Veículo entregue", "Entrega registrada."),
      ],
    },
  ],
  payments: [
    {
      id: "pay-1",
      orderId: "order-3",
      amount: 600,
      method: "PIX",
      status: "Pago",
      paidAt: at(0, 11, 10),
    },
    {
      id: "pay-2",
      orderId: "order-4",
      amount: 570,
      method: "Crédito",
      status: "Pago",
      paidAt: at(-4, 15, 30),
    },
  ],
  appointments: [
    {
      id: "appointment-1",
      customerId: "c2",
      vehicleId: "v2",
      service: "Revisão de 70 mil km",
      scheduledAt: localDateTime(1, 9),
      notes: "Cliente aguardará no local.",
      status: "Agendado",
      createdAt: at(-1),
      updatedAt: at(-1),
    },
    {
      id: "appointment-2",
      customerId: "c4",
      vehicleId: "v4",
      service: "Avaliação da suspensão",
      scheduledAt: localDateTime(0, 14),
      notes: "Confirmado por telefone.",
      status: "Confirmado",
      createdAt: at(-2),
      updatedAt: at(-1),
    },
  ],
  postSales: [
    {
      id: "post-1",
      orderId: "order-4",
      customerId: "c4",
      vehicleId: "v4",
      service: "Revisão de freios",
      scheduledAt: localDateTime(0, 10),
      notes: "Confirmar se o pedal permaneceu firme.",
      status: "Pendente",
      createdAt: at(-4, 16),
    },
    {
      id: "post-2",
      orderId: "order-3",
      customerId: "c3",
      vehicleId: "v3",
      service: "Troca de óleo e filtros",
      scheduledAt: localDateTime(3, 10),
      notes: "Perguntar sobre consumo e vazamentos.",
      status: "Pendente",
      createdAt: at(0, 11),
    },
  ],
  notifications: [
    {
      id: "notification-1",
      kind: "budget-approved",
      title: "Orçamento aprovado",
      message: "Carlos aprovou o orçamento #3006.",
      entityKind: "budget",
      entityId: "budget-3",
      read: false,
      createdAt: at(0, 10, 30),
    },
    {
      id: "notification-2",
      kind: "order-finished",
      title: "OS finalizada",
      message: "OS #852 foi marcada como finalizada.",
      entityKind: "order",
      entityId: "order-3",
      read: false,
      createdAt: at(0, 11),
    },
    {
      id: "notification-3",
      kind: "post-sale",
      title: "Pós-venda",
      message: "Retorno de Ana deve ser realizado hoje.",
      entityKind: "post-sale",
      entityId: "post-1",
      read: false,
      createdAt: at(0, 8),
    },
  ],
};
