import { type CSSProperties, type FormEvent, useEffect, useState } from "react";
import { customerService, localRepository, paymentService, serviceOrderService, settingsService, vehicleService } from "@/lib/repository";
import type { Customer, KaizoData, OrderStatus, PaymentMethod, Priority, ServiceOrder, Vehicle } from "@/lib/types";
import { ClientEvidenceGallery, EvidenceManager } from "@/components/EvidenceGallery";

type Page = "dashboard" | "orders" | "customers" | "vehicles" | "finance" | "settings";
type ModalName = "customer" | "vehicle" | "order" | "payment" | "quote" | null;

const icons: Record<string, string> = { dashboard: "⌂", orders: "▤", customers: "♙", vehicles: "◆", finance: "◒", settings: "⚙", plus: "+", search: "⌕", spark: "✦", arrow: "→", close: "×", menu: "☰", check: "✓", clock: "◷", money: "R$", history: "↺", edit: "✎", trash: "⌫", car: "◇" };
const statusOptions: OrderStatus[] = ["Em diagnóstico", "Orçamento enviado", "Aguardando aprovação", "Aprovado", "Recusado", "Em serviço", "Finalizado", "Cancelado", "Entregue"];
const tagOptions = ["Falha de ignição", "Revisão periódica", "Freio", "Suspensão", "Elétrica", "Estética", "Consumo", "Injeção eletrônica"];
const nav: { id: Page; label: string }[] = [
  { id: "dashboard", label: "Visão geral" }, { id: "orders", label: "Ordens de serviço" }, { id: "customers", label: "Clientes" }, { id: "vehicles", label: "Veículos" }, { id: "finance", label: "Financeiro" }, { id: "settings", label: "Configurações" },
];

const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const currency = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
const formatDate = (value: string, withTime = false) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", ...(withTime ? { hour: "2-digit", minute: "2-digit" } : {}) }).format(new Date(value));
const orderTotal = (order: ServiceOrder) => order.parts.reduce((sum, part) => sum + part.quantity * part.unitPrice, 0) + order.labor.reduce((sum, labor) => sum + labor.price, 0);
const orderCost = (order: ServiceOrder) => order.parts.reduce((sum, part) => sum + part.quantity * part.unitCost, 0) + order.labor.reduce((sum, labor) => sum + labor.estimatedHours * labor.hourlyRate, 0);
const statusClass = (status: string) => `status status-${status.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replaceAll(" ", "-")}`;

function Icon({ name }: { name: string }) { return <span className="icon" aria-hidden="true">{icons[name] ?? "•"}</span>; }
function StatusBadge({ status }: { status: string }) { return <span className={statusClass(status)}>{status}</span>; }

function Modal({ title, subtitle, onClose, children, wide = false }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode; wide?: boolean }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <section className={`modal ${wide ? "modal-wide" : ""}`} role="dialog" aria-modal="true" aria-label={title}>
      <div className="modal-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="Fechar"><Icon name="close" /></button></div>
      {children}
    </section>
  </div>;
}

function Field({ label, children, span = false }: { label: string; children: React.ReactNode; span?: boolean }) { return <label className={`field ${span ? "field-span" : ""}`}><span>{label}</span>{children}</label>; }

function EmptyState({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <div className="empty-state"><span className="empty-symbol">◇</span><h3>{title}</h3><p>{text}</p>{action}</div>; }

export default function KaizoApp() {
  const [data, setData] = useState<KaizoData>(() => localRepository.load());
  const [page, setPage] = useState<Page>("dashboard");
  const [modal, setModal] = useState<ModalName>(null);
  const [selectedOrderId, setSelectedOrderId] = useState<string | null>(null);
  const [selectedCustomerId, setSelectedCustomerId] = useState<string | null>(null);
  const [selectedVehicleId, setSelectedVehicleId] = useState<string | null>(null);
  const [editingCustomer, setEditingCustomer] = useState<Customer | null>(null);
  const [editingVehicle, setEditingVehicle] = useState<Vehicle | null>(null);
  const [toast, setToast] = useState("");
  const [mobileNav, setMobileNav] = useState(false);

  const selectedOrder = data.orders.find((order) => order.id === selectedOrderId) ?? null;

  useEffect(() => {
    if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => undefined);
  }, []);

  useEffect(() => {
    document.documentElement.style.setProperty("--accent", data.company.accent);
  }, [data.company.accent]);

  const commit = (next: KaizoData, message?: string) => {
    setData(next); localRepository.save(next);
    if (message) { setToast(message); window.setTimeout(() => setToast(""), 2600); }
  };

  const upsertOrder = (order: ServiceOrder, message?: string) => commit(serviceOrderService.upsert(data, order), message);
  const addTimeline = (order: ServiceOrder, action: string, description: string): ServiceOrder => ({ ...order, updatedAt: new Date().toISOString(), timeline: [...order.timeline, { id: id("event"), date: new Date().toISOString(), action, description }] });
  const openCustomer = (customer?: Customer) => { setEditingCustomer(customer ?? null); setModal("customer"); };
  const openVehicle = (vehicle?: Vehicle) => { setEditingVehicle(vehicle ?? null); setModal("vehicle"); };
  const go = (next: Page) => { setSelectedOrderId(null); setPage(next); setMobileNav(false); };

  return <div className="app-shell" style={{ "--accent": data.company.accent } as CSSProperties}>
    <aside className={`sidebar ${mobileNav ? "sidebar-open" : ""}`}>
      <button className="brand" onClick={() => go("dashboard")} aria-label="Ir para a visão geral"><img src="/kaizo-logo.png" alt="" /><div><strong>KAIZO</strong><span>GESTÃO AUTOMOTIVA</span></div></button>
      <div className="workspace-card"><span className="workspace-icon">K</span><div><strong>{data.company.name}</strong><small>{data.company.businessType}</small></div><span className="verified">✦</span></div>
      <nav>{nav.map((item) => <button key={item.id} className={page === item.id && !selectedOrder ? "active" : ""} onClick={() => go(item.id)}><Icon name={item.id} /><span>{item.label}</span>{item.id === "orders" && <em>{data.orders.filter((order) => !["Finalizado", "Cancelado", "Entregue"].includes(order.status)).length}</em>}</button>)}</nav>
      <div className="sidebar-foot"><div className="offline-dot" /> <span>Dados salvos neste dispositivo</span></div>
    </aside>
    {mobileNav && <button className="nav-scrim" onClick={() => setMobileNav(false)} aria-label="Fechar menu" />}

    <main className="main">
      <header className="topbar"><button className="menu-button" onClick={() => setMobileNav(true)} aria-label="Abrir menu"><Icon name="menu" /></button><div className="mobile-brand">KAIZO</div><div className="top-actions"><span className="save-state"><i /> sincronizado localmente</span><button className="primary-button compact" onClick={() => setModal("order")}><Icon name="plus" /> Nova OS</button><div className="avatar">OD</div></div></header>
      <div className="content">
        {selectedOrder ? <OrderDetail key={selectedOrder.id} data={data} order={selectedOrder} onBack={() => setSelectedOrderId(null)} onSave={upsertOrder} onPreview={() => setModal("quote")} /> : <>
          {page === "dashboard" && <Dashboard data={data} onNewOrder={() => setModal("order")} onNavigate={go} onOrder={setSelectedOrderId} />}
          {page === "orders" && <Orders data={data} onOrder={setSelectedOrderId} onNew={() => setModal("order")} />}
          {page === "customers" && <Customers data={data} selectedId={selectedCustomerId} onSelect={setSelectedCustomerId} onAdd={() => openCustomer()} onEdit={openCustomer} onDelete={(customer) => { if (data.vehicles.some((v) => v.customerId === customer.id)) return setToast("Remova os veículos vinculados antes de excluir."); if (window.confirm(`Excluir ${customer.name}?`)) commit(customerService.remove(data, customer.id), "Cliente excluído."); }} onOrder={setSelectedOrderId} />}
          {page === "vehicles" && <Vehicles data={data} selectedId={selectedVehicleId} onSelect={setSelectedVehicleId} onAdd={() => openVehicle()} onEdit={openVehicle} onDelete={(vehicle) => { if (data.orders.some((o) => o.vehicleId === vehicle.id)) return setToast("Este veículo possui histórico e não pode ser excluído."); if (window.confirm(`Excluir ${vehicle.plate}?`)) commit(vehicleService.remove(data, vehicle.id), "Veículo excluído."); }} onOrder={setSelectedOrderId} />}
          {page === "finance" && <Finance data={data} onPayment={(orderId) => { setSelectedOrderId(orderId); setModal("payment"); }} onOrder={setSelectedOrderId} />}
          {page === "settings" && <Settings data={data} onSave={(company) => commit(settingsService.update(data, company), "Configurações salvas.")} onReset={() => { if (window.confirm("Restaurar todos os dados de demonstração?")) commit(localRepository.reset(), "Dados de demonstração restaurados."); }} />}
        </>}
      </div>
    </main>

    {modal === "customer" && <CustomerModal customer={editingCustomer} onClose={() => setModal(null)} onSave={(customer) => { commit(customerService.upsert(data, customer), editingCustomer ? "Cliente atualizado." : "Cliente cadastrado."); setModal(null); }} />}
    {modal === "vehicle" && <VehicleModal vehicle={editingVehicle} customers={data.customers} onClose={() => setModal(null)} onSave={(vehicle) => { commit(vehicleService.upsert(data, vehicle), editingVehicle ? "Veículo atualizado." : "Veículo cadastrado."); setModal(null); }} />}
    {modal === "order" && <OrderModal data={data} onClose={() => setModal(null)} onSave={(order) => { const next = serviceOrderService.upsert(data, order); commit(next, `OS #${order.number} criada.`); setModal(null); setPage("orders"); setSelectedOrderId(order.id); }} onQuickCustomer={() => { setModal(null); openCustomer(); }} />}
    {modal === "payment" && selectedOrder && <PaymentModal order={selectedOrder} data={data} onClose={() => setModal(null)} onSave={(payment) => { let next = paymentService.upsert(data, payment); const paid = next.payments.filter((p) => p.orderId === selectedOrder.id).reduce((sum, p) => sum + p.amount, 0); const updatedOrder = addTimeline(selectedOrder, "Pagamento registrado", `${currency(payment.amount)} via ${payment.method}.`); next = serviceOrderService.upsert(next, updatedOrder); commit(next, paid >= orderTotal(selectedOrder) ? "Pagamento integral registrado." : "Pagamento registrado."); setModal(null); }} />}
    {modal === "quote" && selectedOrder && <QuoteModal data={data} order={selectedOrder} onClose={() => setModal(null)} onDecision={(status) => { const next = addTimeline({ ...selectedOrder, status }, status === "Aprovado" ? "Orçamento aprovado" : "Orçamento recusado", status === "Aprovado" ? "Cliente autorizou a execução dos serviços." : "Cliente recusou o orçamento apresentado."); upsertOrder(next, status === "Aprovado" ? "Orçamento aprovado!" : "Orçamento recusado."); setModal(null); }} />}
    {toast && <div className="toast"><Icon name="check" /> {toast}</div>}
  </div>;
}

function Dashboard({ data, onNewOrder, onNavigate, onOrder }: { data: KaizoData; onNewOrder: () => void; onNavigate: (page: Page) => void; onOrder: (id: string) => void }) {
  const active = data.orders.filter((o) => !["Finalizado", "Cancelado", "Entregue"].includes(o.status)).length;
  const waiting = data.orders.filter((o) => o.status === "Aguardando aprovação").length;
  const running = data.orders.filter((o) => o.status === "Em serviço").length;
  const finished = data.orders.filter((o) => o.status === "Finalizado").length;
  const received = data.payments.filter((p) => p.status !== "Pendente").reduce((sum, p) => sum + p.amount, 0);
  return <>
    <div className="page-heading"><div><span className="eyebrow">SEGUNDA-FEIRA, 10 DE AGOSTO</span><h1>Visão geral</h1><p>Bom trabalho. Veja o ritmo da oficina hoje.</p></div><button className="primary-button desktop-action" onClick={onNewOrder}><Icon name="plus" /> Nova ordem de serviço</button></div>
    <section className="metrics-grid">
      <Metric label="Serviços ativos" value={String(active)} delta="2 entraram hoje" icon="spark" tone="yellow" />
      <Metric label="Aguardando aprovação" value={String(waiting)} delta="ação necessária" icon="clock" tone="orange" />
      <Metric label="Em execução" value={String(running)} delta="dentro do prazo" icon="orders" tone="blue" />
      <Metric label="Finalizados hoje" value={String(finished)} delta="meta: 4 serviços" icon="check" tone="green" />
    </section>
    <section className="dashboard-grid">
      <div className="card orders-card"><div className="card-head"><div><span className="section-label">OPERAÇÃO</span><h2>Ordens recentes</h2></div><button className="text-button" onClick={() => onNavigate("orders")}>Ver todas <Icon name="arrow" /></button></div>
        <div className="order-list">{data.orders.slice(0, 4).map((order) => { const vehicle = data.vehicles.find((v) => v.id === order.vehicleId); const customer = data.customers.find((c) => c.id === order.customerId); return <button className="order-row" key={order.id} onClick={() => onOrder(order.id)}><span className="order-number">#{order.number}</span><span className="vehicle-mark"><Icon name="car" /></span><span className="order-main"><strong>{vehicle?.brand} {vehicle?.model}</strong><small>{customer?.name} · {vehicle?.plate}</small></span><StatusBadge status={order.status} /><span className="order-value">{currency(orderTotal(order))}</span><Icon name="arrow" /></button>; })}</div>
      </div>
      <div className="card revenue-card"><div className="card-head"><div><span className="section-label">FINANCEIRO</span><h2>Faturamento do dia</h2></div><span className="trend">+18%</span></div><strong className="big-money">{currency(received)}</strong><p>Recebido em pagamentos confirmados</p><div className="mini-bars" aria-label="Gráfico de faturamento"><i style={{ height: "34%" }} /><i style={{ height: "52%" }} /><i style={{ height: "45%" }} /><i style={{ height: "70%" }} /><i style={{ height: "62%" }} /><i style={{ height: "86%" }} /><i className="active" style={{ height: "100%" }} /></div><button className="secondary-button full" onClick={() => onNavigate("finance")}>Abrir financeiro</button></div>
    </section>
    <section><div className="section-heading"><div><span className="section-label">ACESSO RÁPIDO</span><h2>O que você quer fazer?</h2></div></div><div className="quick-grid"><Quick title="Abrir nova OS" text="Cadastre a entrada do veículo" icon="plus" onClick={onNewOrder} /><Quick title="Ver orçamentos" text="Acompanhe aprovações" icon="orders" onClick={() => onNavigate("orders")} /><Quick title="Novo cliente" text="Mantenha a base atualizada" icon="customers" onClick={() => onNavigate("customers")} /><Quick title="Relatório simples" text="Confira os recebimentos" icon="finance" onClick={() => onNavigate("finance")} /></div></section>
  </>;
}

function Metric({ label, value, delta, icon, tone }: { label: string; value: string; delta: string; icon: string; tone: string }) { return <article className="metric-card"><div className={`metric-icon ${tone}`}><Icon name={icon} /></div><span>{label}</span><strong>{value}</strong><small>{delta}</small></article>; }
function Quick({ title, text, icon, onClick }: { title: string; text: string; icon: string; onClick: () => void }) { return <button className="quick-card" onClick={onClick}><span className="quick-icon"><Icon name={icon} /></span><span><strong>{title}</strong><small>{text}</small></span><Icon name="arrow" /></button>; }

function Orders({ data, onOrder, onNew }: { data: KaizoData; onOrder: (id: string) => void; onNew: () => void }) {
  const [filter, setFilter] = useState("Todos"); const [search, setSearch] = useState("");
  const shown = data.orders.filter((order) => { const customer = data.customers.find((c) => c.id === order.customerId); const vehicle = data.vehicles.find((v) => v.id === order.vehicleId); const matches = `${order.number} ${customer?.name} ${vehicle?.plate} ${vehicle?.model}`.toLowerCase().includes(search.toLowerCase()); return matches && (filter === "Todos" || order.status === filter); });
  return <><div className="page-heading"><div><span className="eyebrow">OPERAÇÃO</span><h1>Ordens de serviço</h1><p>Do diagnóstico à entrega, tudo em um só lugar.</p></div><button className="primary-button" onClick={onNew}><Icon name="plus" /> Nova OS</button></div><div className="toolbar"><div className="search-box"><Icon name="search" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por OS, cliente, placa ou veículo" /></div><select value={filter} onChange={(e) => setFilter(e.target.value)}><option>Todos</option>{statusOptions.map((s) => <option key={s}>{s}</option>)}</select></div>
    <div className="card table-card"><div className="data-table header"><span>Ordem</span><span>Cliente e veículo</span><span>Prazo</span><span>Status</span><span>Valor</span><span /></div>{shown.map((order) => { const c = data.customers.find((x) => x.id === order.customerId); const v = data.vehicles.find((x) => x.id === order.vehicleId); return <button className="data-table" key={order.id} onClick={() => onOrder(order.id)}><span><strong>#{order.number}</strong><small>{formatDate(order.createdAt)}</small></span><span><strong>{v?.brand} {v?.model}</strong><small>{c?.name} · {v?.plate}</small></span><span><strong>{formatDate(order.dueDate)}</strong><small>{order.priority}</small></span><span><StatusBadge status={order.status} /></span><span><strong>{currency(orderTotal(order))}</strong></span><Icon name="arrow" /></button>; })}{shown.length === 0 && <EmptyState title="Nenhuma ordem encontrada" text="Tente ajustar a busca ou os filtros." />}</div></>;
}

function Customers({ data, selectedId, onSelect, onAdd, onEdit, onDelete, onOrder }: { data: KaizoData; selectedId: string | null; onSelect: (id: string | null) => void; onAdd: () => void; onEdit: (c: Customer) => void; onDelete: (c: Customer) => void; onOrder: (id: string) => void }) {
  const [search, setSearch] = useState(""); const shown = data.customers.filter((c) => `${c.name} ${c.phone} ${c.cpf}`.toLowerCase().includes(search.toLowerCase())); const selected = data.customers.find((c) => c.id === selectedId);
  return <><div className="page-heading"><div><span className="eyebrow">RELACIONAMENTO</span><h1>Clientes</h1><p>Histórico e veículos sempre à mão.</p></div><button className="primary-button" onClick={onAdd}><Icon name="plus" /> Novo cliente</button></div><div className={`master-detail ${selected ? "has-detail" : ""}`}><div><div className="search-box standalone"><Icon name="search" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar cliente" /></div><div className="card contact-list">{shown.map((c) => <button key={c.id} className={`contact-row ${selectedId === c.id ? "selected" : ""}`} onClick={() => onSelect(c.id)}><span className="contact-avatar">{c.name.split(" ").slice(0, 2).map((x) => x[0]).join("")}</span><span><strong>{c.name}</strong><small>{c.phone}</small></span><span className="count-pill">{data.vehicles.filter((v) => v.customerId === c.id).length} veículo(s)</span><Icon name="arrow" /></button>)}</div></div>{selected && <aside className="detail-panel"><button className="panel-close" onClick={() => onSelect(null)}><Icon name="close" /></button><span className="contact-avatar large">{selected.name.split(" ").slice(0, 2).map((x) => x[0]).join("")}</span><h2>{selected.name}</h2><p>{selected.phone}</p><div className="detail-actions"><button onClick={() => onEdit(selected)}><Icon name="edit" /> Editar</button><button className="danger" onClick={() => onDelete(selected)}><Icon name="trash" /> Excluir</button></div><h3>Veículos vinculados</h3>{data.vehicles.filter((v) => v.customerId === selected.id).map((v) => <div className="mini-card" key={v.id}><span className="vehicle-mark"><Icon name="car" /></span><span><strong>{v.brand} {v.model}</strong><small>{v.version} · {v.plate}</small></span></div>)}<h3>Ordens relacionadas</h3>{data.orders.filter((o) => o.customerId === selected.id).map((o) => <button className="mini-card clickable" key={o.id} onClick={() => onOrder(o.id)}><span><strong>OS #{o.number}</strong><small>{formatDate(o.createdAt)} · {currency(orderTotal(o))}</small></span><StatusBadge status={o.status} /></button>)}</aside>}</div></>;
}

function Vehicles({ data, selectedId, onSelect, onAdd, onEdit, onDelete, onOrder }: { data: KaizoData; selectedId: string | null; onSelect: (id: string | null) => void; onAdd: () => void; onEdit: (v: Vehicle) => void; onDelete: (v: Vehicle) => void; onOrder: (id: string) => void }) {
  const [search, setSearch] = useState(""); const shown = data.vehicles.filter((v) => { const c = data.customers.find((x) => x.id === v.customerId); return `${v.plate} ${v.brand} ${v.model} ${c?.name}`.toLowerCase().includes(search.toLowerCase()); }); const selected = data.vehicles.find((v) => v.id === selectedId); const customer = data.customers.find((c) => c.id === selected?.customerId); const history = data.orders.filter((o) => o.vehicleId === selectedId);
  return <><div className="page-heading"><div><span className="eyebrow">GARAGEM</span><h1>Veículos</h1><p>Consulte dados e todo o histórico de manutenção.</p></div><button className="primary-button" onClick={onAdd}><Icon name="plus" /> Novo veículo</button></div><div className={`master-detail ${selected ? "has-detail" : ""}`}><div><div className="search-box standalone"><Icon name="search" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por placa, modelo ou cliente" /></div><div className="vehicle-grid">{shown.map((v) => { const c = data.customers.find((x) => x.id === v.customerId); return <button className={`vehicle-card ${selectedId === v.id ? "selected" : ""}`} key={v.id} onClick={() => onSelect(v.id)}><div className="vehicle-visual"><Icon name="car" /><span>{v.year}</span></div><strong>{v.brand} {v.model}</strong><small>{v.version}</small><div><b>{v.plate}</b><span>{c?.name}</span></div></button>; })}</div></div>{selected && <aside className="detail-panel vehicle-history"><button className="panel-close" onClick={() => onSelect(null)}><Icon name="close" /></button><span className="section-label">HISTÓRICO DO VEÍCULO</span><h2>{selected.brand} {selected.model}</h2><p>{selected.version} · {selected.year}</p><div className="vehicle-summary"><div><small>Placa</small><strong>{selected.plate}</strong></div><div><small>Quilometragem</small><strong>{selected.mileage.toLocaleString("pt-BR")} km</strong></div><div><small>Cliente</small><strong>{customer?.name}</strong></div><div><small>Cor</small><strong>{selected.color}</strong></div></div><div className="detail-actions"><button onClick={() => onEdit(selected)}><Icon name="edit" /> Editar</button><button className="danger" onClick={() => onDelete(selected)}><Icon name="trash" /> Excluir</button></div><h3>Serviços anteriores</h3><div className="timeline">{history.map((o) => <button className="timeline-item clickable" key={o.id} onClick={() => onOrder(o.id)}><i /><div><span>OS #{o.number} · {formatDate(o.createdAt)}</span><strong>{o.reportedProblem}</strong><small>{currency(orderTotal(o))} · {o.status}</small></div></button>)}{history.length === 0 && <p className="muted">Nenhum serviço registrado.</p>}</div></aside>}</div></>;
}

function Finance({ data, onPayment, onOrder }: { data: KaizoData; onPayment: (orderId: string) => void; onOrder: (id: string) => void }) {
  const totalReceived = data.payments.reduce((sum, p) => sum + p.amount, 0); const expected = data.orders.filter((o) => !["Cancelado", "Recusado"].includes(o.status)).reduce((sum, o) => sum + orderTotal(o), 0); const pending = Math.max(0, expected - totalReceived); const avg = data.orders.length ? expected / data.orders.length : 0;
  return <><div className="page-heading"><div><span className="eyebrow">RECEBIMENTOS</span><h1>Financeiro</h1><p>Uma visão simples do que entrou e do que falta receber.</p></div></div><section className="metrics-grid"><Metric label="Total recebido" value={currency(totalReceived)} delta="pagamentos confirmados" icon="check" tone="green" /><Metric label="Total pendente" value={currency(pending)} delta="em ordens abertas" icon="clock" tone="orange" /><Metric label="Total orçado" value={currency(expected)} delta={`${data.orders.length} ordens`} icon="orders" tone="yellow" /><Metric label="Ticket médio" value={currency(avg)} delta="por ordem" icon="finance" tone="blue" /></section><div className="card table-card"><div className="card-head padded"><div><span className="section-label">CONTROLE</span><h2>Pagamentos por ordem</h2></div></div><div className="data-table finance-header"><span>OS / Cliente</span><span>Total</span><span>Recebido</span><span>Situação</span><span /></div>{data.orders.filter((o) => o.status !== "Cancelado").map((o) => { const customer = data.customers.find((c) => c.id === o.customerId); const paid = data.payments.filter((p) => p.orderId === o.id).reduce((s, p) => s + p.amount, 0); const total = orderTotal(o); const situation = paid >= total && total > 0 ? "Pago" : paid > 0 ? "Pago parcialmente" : "Pendente"; return <div className="data-table finance-row" key={o.id}><button className="link-cell" onClick={() => onOrder(o.id)}><strong>OS #{o.number}</strong><small>{customer?.name}</small></button><span><strong>{currency(total)}</strong></span><span><strong className="positive">{currency(paid)}</strong></span><span><StatusBadge status={situation} /></span><button className="secondary-button compact" onClick={() => onPayment(o.id)}>{situation === "Pago" ? "Ver / adicionar" : "Registrar pagamento"}</button></div>; })}</div></>;
}

function Settings({ data, onSave, onReset }: { data: KaizoData; onSave: (company: KaizoData["company"]) => void; onReset: () => void }) {
  const [form, setForm] = useState(data.company); const change = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value });
  return <><div className="page-heading"><div><span className="eyebrow">PERSONALIZAÇÃO</span><h1>Configurações</h1><p>As informações aparecem no app e nos orçamentos.</p></div></div><div className="settings-layout"><form className="card settings-form" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><div className="settings-section"><div><span className="section-label">EMPRESA</span><h2>Dados da oficina</h2></div><div className="form-grid"><Field label="Nome da empresa"><input value={form.name} onChange={(e) => change("name", e.target.value)} required /></Field><Field label="Tipo de negócio"><select value={form.businessType} onChange={(e) => change("businessType", e.target.value)}><option>Mecânica</option><option>Elétrica automotiva</option><option>Estética automotiva</option><option>Lava-jato</option><option>Auto center</option><option>Outros</option></select></Field><Field label="WhatsApp"><input value={form.whatsapp} onChange={(e) => change("whatsapp", e.target.value)} /></Field><Field label="Endereço"><input value={form.address} onChange={(e) => change("address", e.target.value)} /></Field><Field label="Mensagem padrão do orçamento" span><textarea rows={4} value={form.quoteMessage} onChange={(e) => change("quoteMessage", e.target.value)} /></Field><Field label="Cor de destaque"><div className="color-field"><input type="color" value={form.accent} onChange={(e) => change("accent", e.target.value)} /><span>{form.accent}</span></div></Field></div></div><div className="form-footer"><button type="button" className="danger-button" onClick={onReset}>Restaurar dados de demonstração</button><button className="primary-button" type="submit">Salvar configurações</button></div></form><aside className="quote-brand-preview"><span className="section-label">PRÉVIA DA MARCA</span><div className="preview-logo"><img src="/kaizo-logo.png" alt="Logo KAIZO" /><div><strong>{form.name}</strong><small>{form.businessType}</small></div></div><p>{form.quoteMessage}</p><span className="accent-preview" style={{ background: form.accent }} /></aside></div></>;
}

function OrderDetail({ data, order, onBack, onSave, onPreview }: { data: KaizoData; order: ServiceOrder; onBack: () => void; onSave: (order: ServiceOrder, message?: string) => void; onPreview: () => void }) {
  const [tab, setTab] = useState<"summary" | "diagnosis" | "budget" | "evidence" | "history">("summary"); const [draft, setDraft] = useState(order); const customer = data.customers.find((c) => c.id === order.customerId); const vehicle = data.vehicles.find((v) => v.id === order.vehicleId); const total = orderTotal(draft); const cost = orderCost(draft); const profit = total - cost;
  const statusChange = (status: OrderStatus) => { const next = { ...draft, status, updatedAt: new Date().toISOString(), timeline: [...draft.timeline, { id: id("event"), date: new Date().toISOString(), action: "Status alterado", description: `Status atualizado para ${status}.` }] }; setDraft(next); onSave(next, "Status atualizado."); };
  return <><button className="back-button" onClick={onBack}>← Voltar para ordens</button><div className="order-hero"><div><div className="order-kicker"><span>ORDEM DE SERVIÇO</span><StatusBadge status={draft.status} /></div><h1>OS #{draft.number}</h1><p>{vehicle?.brand} {vehicle?.model} {vehicle?.version} · <b>{vehicle?.plate}</b></p></div><div className="hero-total"><small>VALOR TOTAL</small><strong>{currency(total)}</strong><span>Entrega: {formatDate(draft.dueDate, true)}</span></div></div><div className="order-context"><div><small>Cliente</small><strong>{customer?.name}</strong><span>{customer?.phone}</span></div><div><small>Quilometragem</small><strong>{draft.mileageIn.toLocaleString("pt-BR")} km</strong><span>na entrada</span></div><div><small>Prioridade</small><strong>{draft.priority}</strong><span>atendimento</span></div><div className="status-select"><small>Status atual</small><select value={draft.status} onChange={(e) => statusChange(e.target.value as OrderStatus)}>{statusOptions.map((s) => <option key={s}>{s}</option>)}</select></div></div><div className="tabs">{[["summary", "Resumo"], ["diagnosis", "Diagnóstico"], ["budget", "Orçamento"], ["evidence", `Evidências${draft.evidences.length ? ` (${draft.evidences.length})` : ""}`], ["history", "Histórico"]].map(([key, label]) => <button className={tab === key ? "active" : ""} key={key} onClick={() => setTab(key as typeof tab)}>{label}</button>)}</div>
    {tab === "summary" && <div className="detail-grid"><div className="card detail-card"><span className="section-label">ENTRADA</span><h2>Problema relatado</h2><p className="detail-copy">{draft.reportedProblem}</p><h3>Observações técnicas</h3><p className="detail-copy muted-copy">{draft.technicalNotes || "Diagnóstico ainda não registrado."}</p><div className="tag-list">{draft.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="card detail-card"><span className="section-label">RESUMO DO ORÇAMENTO</span><div className="summary-line"><span>Peças</span><strong>{currency(draft.parts.reduce((s, p) => s + p.quantity * p.unitPrice, 0))}</strong></div><div className="summary-line"><span>Mão de obra</span><strong>{currency(draft.labor.reduce((s, l) => s + l.price, 0))}</strong></div><div className="summary-line total"><span>Total</span><strong>{currency(total)}</strong></div><button className="primary-button full" onClick={onPreview}>Visualizar orçamento</button></div></div>}
    {tab === "diagnosis" && <form className="card editor-card" onSubmit={(e) => { e.preventDefault(); const next = { ...draft, timeline: [...draft.timeline, { id: id("event"), date: new Date().toISOString(), action: "Diagnóstico alterado", description: "Informações técnicas e recomendações foram atualizadas." }] }; setDraft(next); onSave(next, "Diagnóstico salvo."); }}><div className="form-grid"><Field label="Problema relatado pelo cliente" span><textarea rows={4} value={draft.reportedProblem} onChange={(e) => setDraft({ ...draft, reportedProblem: e.target.value })} /></Field><Field label="Observações técnicas" span><textarea rows={5} value={draft.technicalNotes} onChange={(e) => setDraft({ ...draft, technicalNotes: e.target.value })} /></Field><Field label="Recomendações" span><textarea rows={4} value={draft.recommendations} onChange={(e) => setDraft({ ...draft, recommendations: e.target.value })} /></Field><div className="field field-span"><span>Tags rápidas</span><div className="tag-picker">{tagOptions.map((tag) => <button type="button" key={tag} className={draft.tags.includes(tag) ? "selected" : ""} onClick={() => setDraft({ ...draft, tags: draft.tags.includes(tag) ? draft.tags.filter((x) => x !== tag) : [...draft.tags, tag] })}>{draft.tags.includes(tag) ? "✓ " : "+ "}{tag}</button>)}</div></div></div><div className="form-footer"><button className="primary-button" type="submit">Salvar diagnóstico</button></div></form>}
    {tab === "budget" && <BudgetEditor draft={draft} setDraft={setDraft} total={total} profit={profit} onSave={(message) => onSave({ ...draft, timeline: [...draft.timeline, { id: id("event"), date: new Date().toISOString(), action: "Orçamento atualizado", description: "Itens e valores do orçamento foram salvos." }] }, message)} onPreview={onPreview} onSend={() => { const next = { ...draft, status: "Aguardando aprovação" as OrderStatus, timeline: [...draft.timeline, { id: id("event"), date: new Date().toISOString(), action: "Orçamento enviado", description: "Orçamento disponibilizado para aprovação do cliente." }] }; setDraft(next); onSave(next, "Orçamento enviado para aprovação."); }} />}
    {tab === "evidence" && <EvidenceManager order={draft} onSave={(next, message) => { setDraft(next); onSave(next, message); }} />}
    {tab === "history" && <div className="card history-card"><div className="card-head"><div><span className="section-label">RASTREABILIDADE</span><h2>Linha do tempo da OS</h2></div></div><div className="timeline large-timeline">{[...draft.timeline].reverse().map((event) => <div className="timeline-item" key={event.id}><i /><div><span>{formatDate(event.date, true)}</span><strong>{event.action}</strong><small>{event.description}</small></div></div>)}</div></div>}
  </>;
}

function BudgetEditor({ draft, setDraft, total, profit, onSave, onPreview, onSend }: { draft: ServiceOrder; setDraft: (o: ServiceOrder) => void; total: number; profit: number; onSave: (m: string) => void; onPreview: () => void; onSend: () => void }) {
  const addPart = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); setDraft({ ...draft, parts: [...draft.parts, { id: id("part"), name: String(f.get("name")), supplier: String(f.get("supplier")), quantity: Number(f.get("quantity")), unitCost: Number(f.get("cost")), unitPrice: Number(f.get("price")) }] }); e.currentTarget.reset(); };
  const addLabor = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); setDraft({ ...draft, labor: [...draft.labor, { id: id("labor"), name: String(f.get("name")), estimatedHours: Number(f.get("hours")), hourlyRate: Number(f.get("rate")), price: Number(f.get("price")) }] }); e.currentTarget.reset(); };
  return <div className="budget-layout"><div className="budget-main"><section className="card budget-section"><div className="card-head"><div><span className="section-label">A · PEÇAS</span><h2>Peças e materiais</h2></div></div><div className="budget-table budget-head"><span>Peça / fornecedor</span><span>Qtd.</span><span>Custo</span><span>Cobrado</span><span /></div>{draft.parts.map((part) => <div className="budget-table" key={part.id}><span><strong>{part.name}</strong><small>{part.supplier || "Sem fornecedor"}</small></span><span>{part.quantity}</span><span>{currency(part.unitCost * part.quantity)}</span><span><strong>{currency(part.unitPrice * part.quantity)}</strong></span><button onClick={() => setDraft({ ...draft, parts: draft.parts.filter((p) => p.id !== part.id) })}><Icon name="trash" /></button></div>)}<form className="inline-add" onSubmit={addPart}><input name="name" placeholder="Nome da peça" required /><input name="supplier" placeholder="Fornecedor" /><input name="quantity" type="number" min="1" defaultValue="1" aria-label="Quantidade" required /><input name="cost" type="number" min="0" step="0.01" placeholder="Custo" required /><input name="price" type="number" min="0" step="0.01" placeholder="Cobrado" required /><button className="secondary-button" type="submit"><Icon name="plus" /> Adicionar</button></form></section>
    <section className="card budget-section"><div className="card-head"><div><span className="section-label">B · MÃO DE OBRA</span><h2>Serviços</h2></div></div><div className="budget-table labor budget-head"><span>Serviço</span><span>Tempo</span><span>Hora</span><span>Cobrado</span><span /></div>{draft.labor.map((labor) => <div className="budget-table labor" key={labor.id}><span><strong>{labor.name}</strong></span><span>{labor.estimatedHours}h</span><span>{currency(labor.hourlyRate)}</span><span><strong>{currency(labor.price)}</strong></span><button onClick={() => setDraft({ ...draft, labor: draft.labor.filter((l) => l.id !== labor.id) })}><Icon name="trash" /></button></div>)}<form className="inline-add labor-add" onSubmit={addLabor}><input name="name" placeholder="Nome do serviço" required /><input name="hours" type="number" min="0" step="0.5" placeholder="Horas" required /><input name="rate" type="number" min="0" step="0.01" placeholder="Valor/h" required /><input name="price" type="number" min="0" step="0.01" placeholder="Cobrado" required /><button className="secondary-button" type="submit"><Icon name="plus" /> Adicionar</button></form></section><section className="card budget-section"><Field label="Mensagem da oficina"><textarea rows={4} value={draft.quoteMessage} onChange={(e) => setDraft({ ...draft, quoteMessage: e.target.value })} /></Field></section></div>
    <aside className="card budget-summary"><span className="section-label">C · RESUMO FINANCEIRO</span><h2>Totais do orçamento</h2><div className="summary-line"><span>Custo das peças</span><strong>{currency(draft.parts.reduce((s, p) => s + p.quantity * p.unitCost, 0))}</strong></div><div className="summary-line"><span>Peças cobradas</span><strong>{currency(draft.parts.reduce((s, p) => s + p.quantity * p.unitPrice, 0))}</strong></div><div className="summary-line"><span>Custo mão de obra</span><strong>{currency(draft.labor.reduce((s, l) => s + l.estimatedHours * l.hourlyRate, 0))}</strong></div><div className="summary-line"><span>Mão de obra cobrada</span><strong>{currency(draft.labor.reduce((s, l) => s + l.price, 0))}</strong></div><div className="summary-line total"><span>Total cobrado</span><strong>{currency(total)}</strong></div><div className="profit-box"><span>Lucro estimado</span><strong>{currency(profit)}</strong><small>{total > 0 ? `${((profit / total) * 100).toFixed(1)}% de margem` : "0% de margem"}</small></div><div className="deadline"><Icon name="clock" /><div><small>Prazo estimado</small><strong>{formatDate(draft.dueDate, true)}</strong></div></div><button className="secondary-button full" onClick={() => onSave("Rascunho salvo.")}>Salvar rascunho</button><button className="secondary-button full" onClick={onPreview}>Visualizar orçamento</button><button className="primary-button full" onClick={onSend}>Enviar para aprovação</button></aside></div>;
}

function CustomerModal({ customer, onClose, onSave }: { customer: Customer | null; onClose: () => void; onSave: (c: Customer) => void }) { return <Modal title={customer ? "Editar cliente" : "Novo cliente"} subtitle="Informações essenciais para um atendimento rápido." onClose={onClose}><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); onSave({ id: customer?.id ?? id("customer"), name: String(f.get("name")), phone: String(f.get("phone")), cpf: String(f.get("cpf")), notes: String(f.get("notes")), createdAt: customer?.createdAt ?? new Date().toISOString() }); }}><div className="form-grid"><Field label="Nome completo" span><input name="name" defaultValue={customer?.name} required /></Field><Field label="Telefone / WhatsApp"><input name="phone" defaultValue={customer?.phone} required /></Field><Field label="CPF (opcional)"><input name="cpf" defaultValue={customer?.cpf} /></Field><Field label="Observações" span><textarea name="notes" rows={4} defaultValue={customer?.notes} /></Field></div><div className="form-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button">{customer ? "Salvar alterações" : "Cadastrar cliente"}</button></div></form></Modal>; }

function VehicleModal({ vehicle, customers, onClose, onSave }: { vehicle: Vehicle | null; customers: Customer[]; onClose: () => void; onSave: (v: Vehicle) => void }) { return <Modal title={vehicle ? "Editar veículo" : "Novo veículo"} subtitle="Vincule o veículo ao proprietário correto." onClose={onClose} wide><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); onSave({ id: vehicle?.id ?? id("vehicle"), customerId: String(f.get("customerId")), plate: String(f.get("plate")).toUpperCase(), brand: String(f.get("brand")), model: String(f.get("model")), version: String(f.get("version")), year: Number(f.get("year")), color: String(f.get("color")), mileage: Number(f.get("mileage")), fuel: String(f.get("fuel")), notes: String(f.get("notes")) }); }}><div className="form-grid"><Field label="Cliente vinculado" span><select name="customerId" defaultValue={vehicle?.customerId} required><option value="">Selecione</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Placa"><input name="plate" defaultValue={vehicle?.plate} maxLength={7} required /></Field><Field label="Marca"><input name="brand" defaultValue={vehicle?.brand} required /></Field><Field label="Modelo"><input name="model" defaultValue={vehicle?.model} required /></Field><Field label="Versão"><input name="version" defaultValue={vehicle?.version} /></Field><Field label="Ano"><input name="year" type="number" min="1950" max="2030" defaultValue={vehicle?.year ?? 2020} required /></Field><Field label="Cor"><input name="color" defaultValue={vehicle?.color} /></Field><Field label="Quilometragem"><input name="mileage" type="number" min="0" defaultValue={vehicle?.mileage ?? 0} required /></Field><Field label="Combustível"><select name="fuel" defaultValue={vehicle?.fuel}><option>Flex</option><option>Gasolina</option><option>Etanol</option><option>Diesel</option><option>Elétrico</option><option>Híbrido</option></select></Field><Field label="Observações" span><textarea name="notes" rows={3} defaultValue={vehicle?.notes} /></Field></div><div className="form-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button">Salvar veículo</button></div></form></Modal>; }

function OrderModal({ data, onClose, onSave, onQuickCustomer }: { data: KaizoData; onClose: () => void; onSave: (o: ServiceOrder) => void; onQuickCustomer: () => void }) {
  const [customerId, setCustomerId] = useState(data.customers[0]?.id ?? "");
  const [due] = useState(() => new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 16));
  const vehicles = data.vehicles.filter((vehicle) => vehicle.customerId === customerId);
  return <Modal title="Nova ordem de serviço" subtitle="Registre a entrada do veículo em poucos passos." onClose={onClose} wide><form onSubmit={(event) => {
    event.preventDefault();
    const values = new FormData(event.currentTarget);
    const vehicle = data.vehicles.find((item) => item.id === values.get("vehicleId"));
    const now = new Date().toISOString();
    const number = Math.max(...data.orders.map((item) => item.number), 1200) + 1;
    onSave({
      id: id("order"), number, customerId: String(values.get("customerId")), vehicleId: String(values.get("vehicleId")), mileageIn: Number(values.get("mileage")),
      reportedProblem: String(values.get("problem")), technicalNotes: "", recommendations: "", tags: [], priority: String(values.get("priority")) as Priority,
      dueDate: String(values.get("dueDate")), notes: String(values.get("notes")), status: "Em diagnóstico", parts: [], labor: [], evidences: [],
      quoteMessage: data.company.quoteMessage, createdAt: now, updatedAt: now,
      timeline: [{ id: id("event"), date: now, action: "OS criada", description: `Veículo ${vehicle?.plate} recebido e relato inicial registrado.` }],
    });
  }}><div className="step-label"><b>1</b> Cliente e veículo</div><div className="form-grid"><Field label="Cliente"><select name="customerId" value={customerId} onChange={(event) => setCustomerId(event.target.value)} required>{data.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name} · {customer.phone}</option>)}</select></Field><Field label="Veículo"><select name="vehicleId" required defaultValue=""><option value="" disabled>Selecione o veículo</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.brand} {vehicle.model} · {vehicle.plate}</option>)}</select></Field></div><button className="text-button inline-link" type="button" onClick={onQuickCustomer}>+ Cadastrar novo cliente</button><div className="step-label"><b>2</b> Entrada e diagnóstico inicial</div><div className="form-grid"><Field label="Quilometragem de entrada"><input name="mileage" type="number" min="0" defaultValue={vehicles[0]?.mileage ?? 0} required /></Field><Field label="Prioridade"><select name="priority"><option>Normal</option><option>Alta</option><option>Urgente</option></select></Field><Field label="Problema relatado / descrição" span><textarea name="problem" rows={4} required placeholder="Descreva o que o cliente relatou e os sintomas observados..." /></Field><Field label="Previsão de entrega"><input name="dueDate" type="datetime-local" defaultValue={due} required /></Field><Field label="Observações"><input name="notes" placeholder="Ex.: cliente aguarda retorno por WhatsApp" /></Field></div><div className="form-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button">Criar ordem de serviço</button></div></form></Modal>;
}

function PaymentModal({ order, data, onClose, onSave }: { order: ServiceOrder; data: KaizoData; onClose: () => void; onSave: (p: KaizoData["payments"][number]) => void }) { const paid = data.payments.filter((p) => p.orderId === order.id).reduce((s, p) => s + p.amount, 0); const remaining = Math.max(0, orderTotal(order) - paid); return <Modal title={`Pagamento · OS #${order.number}`} subtitle={`Saldo pendente: ${currency(remaining)}`} onClose={onClose}><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const amount = Number(f.get("amount")); onSave({ id: id("payment"), orderId: order.id, amount, method: String(f.get("method")) as PaymentMethod, status: amount >= remaining ? "Pago" : "Pago parcialmente", paidAt: new Date().toISOString() }); }}><div className="form-grid"><Field label="Valor recebido" span><input name="amount" type="number" min="0.01" step="0.01" max={remaining || undefined} defaultValue={remaining || undefined} required /></Field><Field label="Forma de pagamento" span><select name="method"><option>PIX</option><option>Dinheiro</option><option>Débito</option><option>Crédito</option><option>Transferência</option><option>Outro</option></select></Field></div><div className="form-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button">Registrar pagamento</button></div></form></Modal>; }

function QuoteModal({ data, order, onClose, onDecision }: { data: KaizoData; order: ServiceOrder; onClose: () => void; onDecision: (status: "Aprovado" | "Recusado") => void }) {
  const customer = data.customers.find((item) => item.id === order.customerId);
  const vehicle = data.vehicles.find((item) => item.id === order.vehicleId);
  return <Modal title="Visualização do orçamento" subtitle="Esta é a experiência que o cliente verá." onClose={onClose} wide><div className="quote-preview"><header><div className="quote-company"><img src="/kaizo-logo.png" alt="" /><div><strong>{data.company.name}</strong><small>{data.company.businessType} · {data.company.whatsapp}</small></div></div><StatusBadge status={order.status} /></header><div className="quote-title"><span>ORÇAMENTO · OS #{order.number}</span><h2>{vehicle?.brand} {vehicle?.model} {vehicle?.version}</h2><p>{customer?.name} · {vehicle?.plate}</p></div><div className="quote-columns"><section><h3>Peças</h3>{order.parts.map((part) => <div className="quote-line" key={part.id}><span>{part.quantity}× {part.name}</span><strong>{currency(part.quantity * part.unitPrice)}</strong></div>)}{order.parts.length === 0 && <p className="muted">Nenhuma peça adicionada.</p>}</section><section><h3>Mão de obra</h3>{order.labor.map((labor) => <div className="quote-line" key={labor.id}><span>{labor.name}</span><strong>{currency(labor.price)}</strong></div>)}{order.labor.length === 0 && <p className="muted">Nenhum serviço adicionado.</p>}</section></div><ClientEvidenceGallery order={order} /><div className="quote-total"><span>Total do orçamento</span><strong>{currency(orderTotal(order))}</strong><small>Prazo estimado: {formatDate(order.dueDate, true)}</small></div><p className="quote-message">“{order.quoteMessage || data.company.quoteMessage}”</p><div className="quote-actions"><button className="approve-button" onClick={() => onDecision("Aprovado")}><Icon name="check" /> Aprovar orçamento</button><button className="reject-button" onClick={() => onDecision("Recusado")}><Icon name="close" /> Recusar</button></div></div></Modal>;
}
